### ISSUE TITLE
Graph Ops Missing from python registry

### ISSUE THREAD

**Issue by dakshvar22** [PolyAI-LDN/polyai-models#18]
Hi,

I am loading the `ConveRT` model as :

```
import tensorflow_hub as tfhub
module = tfhub.Module("http://models.poly-ai.com/convert/v1/model.tar.gz")
```

I get the following error while loading the model:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/daksh/miniconda3/envs/work/lib/python3.6/site-packages/tensorflow_hub/module.py", line 170, in __init__
    tags=self._tags)
  File "/Users/daksh/miniconda3/envs/work/lib/python3.6/site-packages/tensorflow_hub/native_module.py", line 340, in _create_impl
    name=name)
  File "/Users/daksh/miniconda3/envs/work/lib/python3.6/site-packages/tensorflow_hub/native_module.py", line 382, in __init__
    op.name for op in self._meta_graph.meta_info_def.stripped_op_list.op})
  File "/Users/daksh/miniconda3/envs/work/lib/python3.6/site-packages/tensorflow_hub/native_module.py", line 822, in register_ops_if_needed
    % missing_ops.difference(set(cpp_registry_ops.keys())))
tensorflow.python.framework.errors_impl.NotFoundError: Graph ops missing from the python registry ({'WordpieceTokenizeWithOffsets'}) are also absent from the c++ registry.
```

Testing with:
Python 3.6.2
Tensorflow 1.14.0
Tensorflow Hub 0.6.0
Tensorflow Text 0.1.0
Mac OS without GPU Support

Same error occurs if I try loading the multi context model.

**Comment by matthen** [comment]
Try importing tensorflow_text first

**Comment by matthen** [comment]
I have clarified this in the main README here: https://github.com/PolyAI-LDN/polyai-models/pull/19

**Comment by dakshvar22** [comment]
Thanks that worked!
